// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package types

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6601e8cdDecodeGithubComTaubyteGoSnarkTypes(in *jlexer.Lexer, out *proofAux) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "pi_a":
			out.A = string(in.String())
		case "pi_b":
			out.B = string(in.String())
		case "pi_c":
			out.C = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComTaubyteGoSnarkTypes(out *jwriter.Writer, in proofAux) {
	out.RawByte('{')
	first := true
	_ = first
	if in.A != "" {
		const prefix string = ",\"pi_a\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.A))
	}
	if in.B != "" {
		const prefix string = ",\"pi_b\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.B))
	}
	if in.C != "" {
		const prefix string = ",\"pi_c\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.C))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v proofAux) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComTaubyteGoSnarkTypes(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v proofAux) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComTaubyteGoSnarkTypes(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *proofAux) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComTaubyteGoSnarkTypes(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *proofAux) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComTaubyteGoSnarkTypes(l, v)
}
